drawings = {"/art/seatedthumb.png": "/art/seated.png",
	        "/art/self3thumb.png": "/art/self3.png",
	        "/art/bodythumb.png": "/art/body.png",
	        "/art/justinthumb.png": "/art/justin.png",
	        "/art/podiumthumb.png": "/art/podium.png",
	        "/art/bearthumb.png": "/art/bear.png",
	        "/art/anonymitythumb.png": "/art/anonymity.png",
	        "/art/viticulturethumb.png": "/art/viticulture.png",
	        "/art/femalethumb.png": "/art/female.png",
	        "/art/smilethumb.png": "/art/smile.png"}

paintings = {"/art/danthumb.png": "/art/dan.png",
             "/art/tootthumb.png": "/art/toot.png",
             "/art/chancetimethumb.png": "/art/chancetime.png",
             "/art/gourdthumb.png": "art/gourd.png",
             "/art/perfectionthumb.png": "/art/perfection.png",
             "/art/racecarthumb.png": "/art/racecar.png",
             "/art/pondthumb.png": "/art/pond.png",
             "/art/shotthumb.png": "/art/shot/png"}
             
digital = {"/art/armadillothumb.png": "/art/armadillo.png",
		   "/art/farmthumb.png": "/art/farm.png",
		   "/art/heartthumb.png": "/art/heart.png",
		   "/art/metalelissathumb.png": "/art/metalelissa.png"}

lloyd = ["/art/lloyd1.png",
		 "/art/lloyd2.png",
		 "/art/lloyd3.png",
		 "/art/lloyd4.png",
		 "/art/lloyd5.png",
		 "/art/lloyd6.png",
		 "/art/lloyd7.png",
		 "/art/lloyd8.png",
		 "/art/lloyd9.png",
		 "/art/lloyd10.png",
		 "/art/lloyd11.png",
		 "/art/lloyd12.png",
		 "/art/lloyd13.png",
		 "/art/lloyd14.png",
		 "/art/lloyd15.png",
		 "/art/lloyd16.png",
		 "/art/lloyd17.png",
		 "/art/lloyd18.png",
		 "/art/lloyd19.png",
		 "/art/lloyd20.png",
		 "/art/lloyd21.png",
		 "/art/lloyd22.png",
		 "/art/lloyd23.png",
		 "/art/lloyd24.png",
		 "/art/lloyd25.png",
		 "/art/lloyd26.png",
		 "/art/lloyd27.png",
		 "/art/lloyd28.png",]
			

